// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdsVCOYicIvNtlrmNIHnGodXzgscPbyI',
    appId: '1:670718147340:android:c46caa27ab1aeeb439e729',
    messagingSenderId: '670718147340',
    projectId: 'farmerapp-50615',
    storageBucket: 'farmerapp-50615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMyRmZGACB-brJbk5K09A_Xe9pn9-Mmb8',
    appId: '1:670718147340:ios:afdeee276491aa4139e729',
    messagingSenderId: '670718147340',
    projectId: 'farmerapp-50615',
    storageBucket: 'farmerapp-50615.appspot.com',
    androidClientId: '670718147340-73gbid0f2549psq47hqhb6e601d7ol7q.apps.googleusercontent.com',
    iosClientId: '670718147340-sofbqhts6dd17j3o5i42e9vupv40tpq0.apps.googleusercontent.com',
    iosBundleId: 'com.agnext.farmerApp.farmerApp',
  );
}
